G-Node/nix

- src/util/dataAccess.cpp
- test/TestDataAccess.cpp
[dataAccess] fixed segfault bug in getOffsetAndCount, added test
If the tag had no units there was an access into an empty units vector
> Fix for segmentation fault (issue #430)

- include/nix/DataArray.hpp
- include/nix/Exception.hpp
- test/TestDataArray.cpp
So far, DataArray::appendRangeDimension(ticks) with empty ticks vector led to an HDF5 Exception which was shown as unidentifiable C++ Exception in nixpy, actually providing no information about the real cause.
> DataArray throws a proper exception if range dim with empty ticks is created

- include/nix/hdf5/Attribute.hpp
- include/nix/hdf5/BaseHDF5.hpp
- include/nix/hdf5/DataSetHDF5.hpp
- include/nix/hdf5/Group.hpp
- include/nix/hdf5/LocID.hpp
- src/hdf5/Attribute.cpp
- src/hdf5/BaseHDF5.cpp
- src/hdf5/DataSetHDF5.cpp
- src/hdf5/Group.cpp
- src/hdf5/LocID.cpp
Another step in getting rid of H5Cpp bindings completely (cf. issue #452).
> Attribute: new slim wrapper for H5 attributes

- include/nix/hdf5/BaseHDF5.hpp
- include/nix/hdf5/DataSetHDF5.hpp
- include/nix/hdf5/Group.hpp
- include/nix/hdf5/LocID.hpp
- src/hdf5/Attribute.cpp
- src/hdf5/BaseHDF5.cpp
- src/hdf5/DataSetHDF5.cpp
- src/hdf5/DataSpace.cpp
- src/hdf5/FileHDF5.cpp
- src/hdf5/Group.cpp
- src/hdf5/LocID.cpp
- test/RefTester.hpp
- test/TestDataSet.cpp
- test/TestGroup.cpp
- test/TestH5.cpp
`BaseHDF5::BaseHDF5(hid_t)` used to do a `inc()`, i.e making a
copy of the object. It now takes over ownership by not doing that
`inc()`. This allows code like `Group g = H5Gopen()` instead of
the longer version`hid_t o = H5Gopen(); Group g = o; H5Idec_ref(o);`.
> H5::BaseHDF5: change ref-count behaviour of hid_t ctor

- .travis.ctest
- .travis.yml
- Use `compiler` directive instead of custom matrix+env variables
- Only install g++-4.8 for g++ builds
- Use `update-alternatives` to select g++-4.8
> [travis] cleanup travis file

- include/nix/Hydra.hpp
- include/nix/NDSize.hpp
- include/nix/hydra/multiArray.hpp
- src/NDArray.cpp
- src/hdf5/DataSetHDF5.cpp
- src/hdf5/Group.cpp
- src/hdf5/PropertyHDF5.cpp
- src/util/dataAccess.cpp
- test/TestH5.cpp
This should fix all build warnings on windows (32bit & 64bit),
i.e. close issue #447. Although not all are properly fixed since
that requires some refactoring (issue #473).
> [m32] Fix warnings on win32

- include/nix/valid/checks.hpp
- src/valid/checks.cpp
- src/valid/validate.cpp
- src/valid/validator.cpp
- test/TestDataArray.cpp
- test/TestValidate.cpp
major changes to the validation:
mismatch in dimension count is an error
mismatch in tick count is an error
mismatch in label count is a warning (they are optional)
and several minors ...
> Remove the const refs in check.cpp and some work on the validation

- README.md
```
E: Unable to locate package nixlib-dev
```
> README.md: fix pkg name (nixlib-dev → libnix-dev)

- include/nix/File.hpp
- test/TestFile.cpp
solves issue #506 
actually I introduce  a slight inconsistency here. So far the getXYZ(index) methods return none (e.g. in Block) when an invalid index is given. I do not really like this and would prefer the exception. If you disagree I am happy to change the behaviour in File to match the Block-like behaviour and remove the exception.
> [File] throw nix::outOfBounds exception if invalid index is used

- src/Section.cpp
- src/Source.cpp
with pr #512 I changed the << operators to the same version as in all other entities. With these changes, nixpy would compile but tests failed during nix import due to undefined symbols.
This commit reverts these changes. Still, I do not really understand but this may come later ...
> [<< operators] in Section and Source reverted back to pre pr #512 state

- include/nix/Property.hpp
- include/nix/base/IProperty.hpp
- include/nix/hdf5/PropertyHDF5.hpp
- src/Property.cpp
- src/hdf5/PropertyHDF5.cpp
this pr solves issue #525.  Actually, this is the only method that can be meaningfully moved. The == and != have to stay with the back end as long as we check for equality by being stored at the same location in the hdf5 file.
> [Property] move compare method to the front-end

- include/nix/DataType.hpp
- src/DataType.cpp
- src/hdf5/DataTypeHDF5.cpp
- test/TestDataSet.cpp
- test/TestValue.cpp
Not supported anyway. Fix all locations that mention it.
NB: This will break nixpy and nix-java bindings.
> DataType: remove Date, DateTime

- CMakeLists.txt
Otherwise if nix is installed in /usr/local and
this path in before the local search path, the
system nix header will be used; this can and will
lead to conflicts.
> [cmake] search in local dirs BEFORE other dirs

- include/nix/DataArray.hpp
- include/nix/DataView.hpp
- include/nix/hdf5/BlockHDF5.hpp
- include/nix/hdf5/FileHDF5.hpp
This is a band aid for gh issue #537 by removing
the minority of override. Since clang complains
about inconsistent use, this will fix the warning.
Better would be to use override everywhere, after
the 1.1. release.
> Be consistent with 'override'

- include/nix/DataType.hpp
* For consistency reasons
* And lets hope this causes less troubles with nix-java
> DataType: check for _WIN32 instead of WIN32

- include/nix/base/Entity.hpp
- include/nix/base/IEntity.hpp
- include/nix/hdf5/BlockHDF5.hpp
- include/nix/hdf5/DataSetHDF5.hpp
- include/nix/hdf5/EntityHDF5.hpp
- include/nix/hdf5/H5Group.hpp
- include/nix/hdf5/PropertyHDF5.hpp
- src/hdf5/DataSetHDF5.cpp
- src/hdf5/EntityHDF5.cpp
- src/hdf5/H5Group.cpp
- src/hdf5/PropertyHDF5.cpp
- test/BaseTestEntity.cpp
- test/BaseTestEntity.hpp
- test/BaseTestProperty.cpp
- test/BaseTestProperty.hpp
- test/TestEntityHDF5.hpp
- test/TestPropertyHDF5.hpp
In hdf5 an hid identifier can be valid even if the object is unlinked from everything else in the file, the object's name, btw., does no longer exist at that point. According to the valid hid, there may still be a reference count from this object to attributes and datasets. These can still be accessed.
This pr is related to issue #565
> add a way to check whether an Entity is valid in the backend

- include/nix/Variant.hpp
- src/Variant.cpp
Implement swap in terms of assignment not the other way around.
Simplifies the code a bit.
> Variant: Rework assignment, move ctor and swap

- include/nix/Variant.hpp
And fix issue #578 (resp. #570, for good, hopefully).
> Variant: properly specialise get<none_t>

- CMakeLists.txt
The backend separation pr #585 broke build with `-DBUILD_TESTING=OFF`.
Fix that.
> [cmake] always add the backend path to includes

- backend/hdf5/DataArrayHDF5.cpp
- backend/hdf5/PropertyHDF5.cpp
- backend/hdf5/h5x/H5DataSet.cpp
- backend/hdf5/h5x/H5DataSet.hpp
- backend/hdf5/h5x/H5DataType.cpp
- backend/hdf5/h5x/H5DataType.hpp
- test/hdf5/TestDataSet.cpp
Part of the ongoing effort to separate the hdf5 backend code
from our hdf5 abstraction layer.
> h5x::DataSet::dataType() returns a h5x::DataType

- backend/fs/BlockFS.hpp
- backend/fs/FileFS.hpp
This will otherwise trigger clang's inconsistent-missing-override
warning.
> [fs] File: don't mark close() with 'override'

- backend/hdf5/h5x/H5Group.cpp
- test/hdf5/TestH5Group.cpp
- test/hdf5/TestH5Group.hpp
Use correct index type and order in `H5Lget_name_by_idx`: `H5_INDEX_CRT_ORDER` and `H5_ITER_INC` respectively.
File and Group in TestH5Group updated to enable order tracking and a new test has been added that checks whether retrieval order follows creation order.
Resolves #617.
> Use order tracking for H5Group::objectName

- backend/fs/SectionFS.cpp
- backend/fs/SectionFS.hpp
- backend/hdf5/SectionHDF5.cpp
- backend/hdf5/SectionHDF5.hpp
- include/nix/Section.hpp
- include/nix/base/ISection.hpp
- include/nix/util/filter.hpp
- src/Section.cpp
- test/BaseTestSection.cpp
- test/BaseTestSection.hpp
- test/fs/TestSectionFS.hpp
- test/hdf5/TestSectionHDF5.hpp
This pr introduces the long missing convenience methods for inverse search from Sections to referring entities(issue #551). Unfortunately, it is not possible to implement the functionality using templates due to circular includes. 
This relates to issue #560.
> Inverse search of DataArrays, Tags, etc.. from a section

- backend/fs/EntityWithSourcesFS.cpp
- backend/fs/SourceFS.cpp
- backend/fs/SourceFS.hpp
- backend/hdf5/SourceHDF5.cpp
- backend/hdf5/SourceHDF5.hpp
- include/nix/Source.hpp
- include/nix/base/ISource.hpp
- include/nix/util/filter.hpp
- src/Source.cpp
- test/BaseTestSource.cpp
- test/BaseTestSource.hpp
- test/fs/TestSourceFS.hpp
- test/hdf5/TestSourceHDF5.hpp
Implementation is not optimal since we do not have a direct access to the block in which the source resides. Thus, the methods search across all Blocks...
> Inverse search of DataArrays, Tags, etc.. from a Source

- backend/hdf5/PropertyHDF5.cpp
- backend/hdf5/h5x/H5DataType.cpp
- backend/hdf5/h5x/H5DataType.hpp
- include/nix/Platform.hpp
Booleans are now stored as enums with members "FALSE" and "TRUE".
Fixes issue #635.
> New boolean representation

- backend/hdf5/h5x/H5DataType.cpp
Registers a converter in HDF5 for reading `H5T_STD_B8LE`, the old boolean type, found in files.
Notice that the converter doesn't really do anything. I suspect it might be implicitly casting data to the destination type though I haven't found a definitive description in the HDF5 documentation that explains this.
If you think it's better that we define an explicit conversion path, for instance if the current method is simply exploiting behaviour that is not guaranteed, I'll do it and push to this PR.
> Read bitfields as booleans

- include/nix/Version.hpp
Currently `nixversion.hpp` is included from `Version.hpp` outside the include guards and therefore the version numbers might get unnecessarily redefined. Fix this by moving it inside `Version.hpp`'s guards.
> [Version] move nixversion include inside guards

- backend/hdf5/PropertyHDF5.cpp
- include/nix/Platform.hpp
When building `nix` using `gcc@4.9.2` and `openmpi@2.0.1`, we get:
```
from /path_to/nix-1.3.2/src/DataArray.cpp:12:
/path_to/nix-1.3.2/include/nix/Platform.hpp:38:38: error: declaration does not declare anything [-fpermissive]
```
We tracked back and found a type `PACKED` in https://github.com/open-mpi/ompi/blob/master/ompi/mpi/cxx/constants.h#L128
```
OMPI_DECLSPEC extern const Datatype PACKED;
```
which gets replaced by the preprocessor:
```
OMPI_DECLSPEC extern const Datatype __attribute__((packed));
```
We did a short test using build llvm/clang 3.9.0 but could not reproduce this problem; it could be a compiler version-specific issue.
> Prefix PACKED macro to avoid clash with openmpi's PACKED type

- CONTRIBUTING.md
- GSoC.md
Also renamed Contributing.md to CONTRIBUTING.md for consistency with other projects.
> Adding GSoC contribution guide

- backend/fs/BaseTagFS.cpp
- backend/fs/GroupFS.cpp
- backend/hdf5/BaseTagHDF5.cpp
- backend/hdf5/GroupHDF5.cpp
- src/Block.cpp
- src/MultiTag.cpp
- src/Tag.cpp
all(?!) vector setters verify entity identity by name and id
change behaviour of has-, add-, removeEntity methods to use the name instead of the id
> Fixing bug #672

- .dir-locals.el
- .editorconfig
Help editors doing the right thing for various files using the
editorconfig standard: http://editorconfig.org
> Editors: add editorconfig, ns indent for emacs

- CMakeLists.txt
The former is deprecated for quite some time (at least since FindHDF5 3.0).
https://cmake.org/cmake/help/v3.5/module/FindHDF5.html
Kind of broke for me during the "tübingenhackathon" and the +d fixed it.
> [Cmake] HDF5_INCLUDE_DIR -> HDF5_INCLUDE_DIRS

- include/nix/Section.hpp
- src/Section.cpp
- test/BaseTestSection.cpp
Due to our recent changes in findSection (exclude of the root section) the findRelated did not work properly in all cases (not caught by the tests :( ).
Extended the test cases and simplified findRelated, should fix #691
> Fix findRelated 

- CMakeLists.txt
- include/nix/Platform.hpp
Use -DBUILD_STATIC on the cmake command line to enable a static
build of NIX, which includes linking boost and hdf5 statically
into a static version of NIX.
> [build] optional static build of NIX

- include/nix/base/types.hpp
For reasons lost to history some templates were explicitly
instantiated, most likely to fix some windows build issues.
This seems to be hopefully not necessary anymore, becasue it
breaks builds on ARM. It is also violating the C++ std (14.7
clause 5):
"an explicit instantiation definition shall appear at
most once in a program"
> Fix ARM build: remove explicit tmpl instantiation

- include/nix/DataArray.hpp
- src/DataArray.cpp
- src/Property.cpp
- test/BaseTestDataArray.cpp
- test/BaseTestProperty.cpp
relaxed the unit handling at two places:
1) ``Properties`` may have non-SI units. Passing an empty string, or one that consists of only blanks, will remove the unit from the property.
2) ``DataArrays``: The value unit may be non-SI. In case the dimensionality of the ``DataArray`` is 1-D and the first dimension is an ``AliasRangeDimension`` setting an non-SI will lead to an exception.
In case a non-SI unit is set, the attempt of adding an ``AliasRangeDimension`` will lead to an exception.
Data retrieval functions behave as before: if there are units and theses can not be scaled, an exception will be thrown.
> Unit handling

- backend/hdf5/h5x/H5DataType.cpp
- backend/hdf5/h5x/H5DataType.hpp
- test/hdf5/TestH5.cpp
Split out from the DataFrame branch, to keep that PR as small as possible.
> Small h5x::DataType improvements

- CMakeLists.txt
- nixio.pc.in
In accordance to the long term plan to rename many components
of NIX to nixio to avoid name clashing we should also be called
nixio.pc for pkg-config files.
This is issue #626
> [cmake/pkg-config] nix.pc -> nixio.pc

- backend/fs/PropertyFS.cpp
- backend/fs/PropertyFS.hpp
- backend/fs/SectionFS.cpp
- backend/fs/SectionFS.hpp
- backend/hdf5/PropertyHDF5.cpp
- backend/hdf5/PropertyHDF5.hpp
- backend/hdf5/SectionHDF5.cpp
- backend/hdf5/SectionHDF5.hpp
- cli/modules/Dump.cpp
- include/nix/Property.hpp
- include/nix/Section.hpp
- include/nix/base/IProperty.hpp
- include/nix/base/ISection.hpp
- src/Property.cpp
- src/Section.cpp
- test/BaseTestProperty.cpp
- test/BaseTestProperty.hpp
- test/BaseTestReadOnly.cpp
- test/BaseTestSection.cpp
- test/BaseTestSection.hpp
- test/TestOptionalObligatory.cpp
- test/TestOptionalObligatory.hpp
- test/fs/TestPropertyFS.hpp
- test/fs/TestSectionFS.hpp
- test/hdf5/TestPropertyHDF5.hpp
- test/hdf5/TestSectionHDF5.hpp
The property is now a dataset with a simple data type, no compound type anymore.
Implementation is based on the old value implementation. Maybe there are more elegant ways.
Value class still exists.
Feel free to speak your mind.
> remove Values, move uncertainty to property fixes #550

- appveyor.yml
- include/nix/DataArray.hpp
- include/nix/Dimensions.hpp
- include/nix/MultiTag.hpp
- include/nix/Platform.hpp
- include/nix/Tag.hpp
- include/nix/util/dataAccess.hpp
- src/Dimensions.cpp
- src/MultiTag.cpp
- src/util/dataAccess.cpp
- test/BaseTestDataAccess.cpp
- test/BaseTestDataAccess.hpp
- test/BaseTestDataArray.cpp
- test/BaseTestDimension.cpp
- test/BaseTestMultiTag.cpp
- test/BaseTestTag.cpp
- test/hdf5/TestDataAccessHDF5.hpp
With this PR, it is possible to get several tagged slices with one call. In case the referenced DataArray has a RangeDimension, this should greatly improve the performance for it reduces the fileio dramatically. 
A few functions have been deprecated (9daaad6 ).
I changed the behavior of the indexOf function in RangeDimensions. Previously, we returned the index of the tick that is equal or greater than the position. Now it is less or equal, which in my view makes a lot more sense, so I tend to consider the previous behaviour a bug. Docs of Tag and MTag were updated to state this explicitly. Tests were adapted
> Retrieve multiple tagged data slices in one go

- backend/fs/BlockFS.cpp
- backend/hdf5/BlockHDF5.cpp
The Block constructor used for existing blocks, i.e., when a Block is
created through getBlock(), did not have a default 'compr' value, which
would cause issues with uninitialised values.
It's now initialised to Compression::Auto.
> Add default Compression::Auto to Block constructor

- CMakeLists.txt
So, HDF5 1.10.3 introduced some breaking API change with a minor
version update. Lets blame us for not specifying that we want
indeed the 1.10. API; We do this now (H5_USE_110_API) which should
fix the issue and hopefully prevent future API breaks. Hands up
for everyone who thinks that you need to specify H5_USE_110_API
to not break when upgrading from 1.10.2 to 1.10.3 is confusing,
to put it mildly.
TLDR: assert we want the 1.10 API by specify H5_USE_110_API.
> [cmake] fix compilation for hdf5 1.10.3

- CMakeLists.txt
this pr is part of the nix-mx, brew installation problem solution. This pr:
* disables the nix-tool build for the static build
* renames the static lib under win to allow for installing shared and static lib
* checks whether a pkgcfg file already exists, only if missing it is installed
We should be able to install static and shared lib in parallel without brew complaining about overwriting   links 🤞
> nix-tool only for shared library build

- src/util/dataAccess.cpp
- test/BaseTestDataAccess.cpp
with this pr, the ``util::dataSlice`` method automatically fills in missing information (to some extent). That is: start, end, and unit values may be missing or incomplete. If less info is given than there are dimensions defaults are assumed:
* ``units`` are filled with the ones defined in the dimension
* ``start`` is set to ``offset`` (``SampledDimension``), first tick (``RangeDimension``), or 0 (``SetDimension``)
* ``end`` is set to point (``SampledDimension``, ``RangeDimension``) or max index (``SetDimension``)
General rule: if information is provided, the first value given is assumed to belong to the first dimension the 2nd to the second, etc.
> data slice can live with less information

- README.md
- docs/index.md
Since we created the G-Node user on Appveyor and moved all official builds to that user, badges and links should be taken from that build.
> Link to G-Node owned Appveyor project and badges

- backend/hdf5/FileHDF5.cpp
- backend/hdf5/FileHDF5.hpp
- backend/hdf5/PropertyHDF5.cpp
- backend/hdf5/PropertyHDF5.hpp
- include/nix/Version.hpp
- test/TestVersion.cpp
- test/TestVersion.hpp
With this pr the 1.5 version is able to read old metadata. Values are internally converted to Variant. Caveat: uncertainty returns only the uncertainty of the first value. No further consistency check is done
> Downward reading of old style properties resp. values

- .github/workflows/ci.yml
- CMakeLists.txt
- test/hdf5/TestEntityHDF5.hpp
Use GH actions/workflows as CI. Should be equivalent to travis. Replaces PR #781 (which was done from my fork and didn't trigger the actions). Lets see if this does.
> [CI] Use github actions/workflows as CI

- include/nix/DataView.hpp
- test/BaseTestDataAccess.cpp
Check the dimensions of offset and count on DataView creation and throw
appropriate exception.
Fixes #786.
> DataView: Check dims on create

- docs/validation.rst
Rules for the shape of MultiTag positions and extents were a bit unclear.  New description should make things clearer.
We discussed this on Slack and I forgot to add it to the previous PR before it was merged.
> [docs] Clarification on rules for MultiTag

- CMakeLists.txt
- nixio.spec
- src/util/dataAccess.cpp
- src/valid/checks.cpp
- test/BaseTestDataAccess.cpp
- test/BaseTestDataAccess.hpp
- test/TestValidate.cpp
- test/hdf5/TestDataAccessHDF5.hpp
addresses #800 but only for 1.4
> Tag flexibility

- backend/hdf5/SectionHDF5.cpp
- backend/hdf5/SectionHDF5.hpp
So far we set chunking to auto and hence properties reserved quite a bit of unnecessary overhead. With this PR, the default size is reduced to 8 entries for Properties that are created without or only a single value. If they are created with a vector of values, the vector size is used to define the size and the chunking of the H5 dataset. 
Compression has been switched on.
These changes are analogous to recent nixpy changes
> Change creation of Properties

- backend/hdf5/h5x/Attribute.cpp
- backend/hdf5/h5x/Attribute.hpp
- backend/hdf5/h5x/H5DataType.cpp
- backend/hdf5/h5x/H5DataType.hpp
- backend/hdf5/h5x/H5Group.cpp
- backend/hdf5/h5x/H5Group.hpp
- backend/hdf5/h5x/H5PList.hpp
- backend/hdf5/h5x/H5Plist.cpp
- backend/hdf5/h5x/LocID.cpp
- backend/hdf5/h5x/LocID.hpp
- test/hdf5/TestH5.cpp
- test/hdf5/TestH5.hpp
This enables utf8 encoding for the names of groups, datasets and links as well as for all string values in datasets and attributes.
Closes #779
> UTF-8 encoding of all strings for names and contents

- include/nix/Dimensions.hpp
- include/nix/util/dataAccess.hpp
- src/Dimensions.cpp
- src/util/dataAccess.cpp
- test/BaseTestDataAccess.cpp
- test/BaseTestDataAccess.hpp
- test/BaseTestDimension.cpp
- test/BaseTestDimension.hpp
- test/hdf5/TestDataAccessHDF5.hpp
- test/hdf5/TestDimensionHDF5.hpp
This pull request is the first step for fixing the issue raised in #818 
Adds some overloads to the RangeDimension::indexOf method family that allow for some behavior controlling. Unfortunately, the original indexOf behavior needed to be altered a bit. Invalid positions will not raise an exception. There is, however a new method that allows for cheking if a position is in range.
I made some decisions I would like to discuss:
1. is it a good idea to allow end be less than start? At the moment I check and simply swap the variables (line 467 in Dimension.cpp).
2. is it a good idea to silently ignore invalid ranges? Currently they are simply not part of the result vector. Alternatively the vector could contain optionals.
3. The method for getting start and end indices of a single range (start …
> adaptations for RangeDimension indexOf methods

- .travis.yml
- dockerfiles/archlinux.Dockerfile
Set PKGEXT to 'pkg.tar'
- Makes build slightly faster (no compression).
Use wildcards to install aur built packages:
- Makes dockerfile version independent, otherwise it would break every
time one of the packages was updated.
> [dockerfile/arch] Fix aur package installation

- .travis.yml
- src/File.cpp
Explicitly instantiate a boost::filesystem::path object to avoid
any ambiguity via implicit type conversion; as seems to be happen
with boost 1.71:
/src/src/File.cpp: In static member function ‘static nix::File nix::File::open(const string&, nix::FileMode, const string&, nix::Compression, nix::OpenFlags)’:
/src/src/File.cpp:29:63: error: call of overloaded ‘exists(<brace-enclosed initializer list>)’ is ambiguous
29 |     if (mode == nix::FileMode::ReadOnly && !bfs::exists({name})) {
|                                                               ^
In file included from /usr/include/boost/filesystem.hpp:17,
from /src/src/File.cpp:18:
/usr/include/boost/filesystem/operations.hpp:463:8: note: candidate: ‘bool boost::filesystem::exists(const boost::filesystem::path&)’
463 |   bool …
> [File] disambiguate bfs::exist constructor

- .github/workflows/build-test.yml
- README.md
This PR adds a viable github actions build - test setup for Ubuntu gcc/clang and MacOS.
Also removed the travis-CI build requirement for the master branch, since Travis is no longer accepting jobs.
> Add gh-actions build
