G-Node/nix

- include/nix/Block.hpp
- include/nix/Feature.hpp
- include/nix/File.hpp
- include/nix/base/IBlock.hpp
- include/nix/base/IFeature.hpp
- include/nix/hdf5/BlockHDF5.hpp
- include/nix/hdf5/FeatureHDF5.hpp
- include/nix/hdf5/FileHDF5.hpp
- src/hdf5/FeatureHDF5.cpp
other objects in separate PRs, to avoid huge PR
> name_or_id clean-up for Block, File and Feature

- include/nix/MultiTag.hpp
- include/nix/base/IMultiTag.hpp
- include/nix/hdf5/MultiTagHDF5.hpp
- src/hdf5/MultiTagHDF5.cpp
- test/TestMultiTag.cpp
TODO: determine whether removeReference should also accept name
> name_or_id clean up for MultiTag

- include/nix/hdf5/ExceptionHDF5.hpp
- src/hdf5/Group.cpp
> Group: clean up error/exception handling

- include/nix/Hydra.hpp
- include/nix/valid/conditions.hpp
- src/util/util.cpp
This makes all test pass on win32 in my VM.
> Windows related test fixes

- include/nix/NDSize.hpp
- include/nix/Platform.hpp
- src/Dimensions.cpp
- test/TestDataSet.cpp
> [win] Fix some build warnings

- include/nix/NDSize.hpp
- include/nix/hdf5/DimensionHDF5.hpp
- include/nix/hdf5/ExceptionHDF5.hpp
> [win] more build warning fixes

- include/nix/hdf5/Group.hpp
- include/nix/hdf5/LocID.hpp
- src/hdf5/Group.cpp
- src/hdf5/LocID.cpp
- test/TestValue.hpp
> H5: Remove all usages of H5::Group

- include/nix/hdf5/BaseHDF5.hpp
- include/nix/hdf5/LocID.hpp
- src/hdf5/BaseHDF5.cpp
- src/hdf5/Group.cpp
- src/hdf5/LocID.cpp
- test/TestH5.cpp
- test/TestH5.hpp
Replaces some nasty new+delete in the code.
> H5: Wrap H5Iget_name and use it

- include/nix/Exception.hpp
> Fix use-after-free errors in custom exceptions

- cli/modules/Dump.cpp
- cli/modules/Dump.hpp
- include/nix/Hydra.hpp
- include/nix/NDSize.hpp
- include/nix/hdf5/DimensionHDF5.hpp
- include/nix/hydra/multiArray.hpp
- include/nix/util/filter.hpp
- include/nix/util/util.hpp
- src/NDSize.cpp
- src/hdf5/DataSetHDF5.cpp
- src/hdf5/MultiTagHDF5.cpp
- src/util/dataAccess.cpp
- src/util/util.cpp
- test/TestBlock.hpp
- test/TestDataAccess.cpp
- test/TestDataAccess.hpp
- test/TestDataArray.hpp
- test/TestDataSet.cpp
- test/TestDataSet.hpp
- test/TestGroup.hpp
- test/TestMultiTag.hpp
- test/TestOptionalObligatory.cpp
- test/TestOptionalObligatory.hpp
- test/TestSource.hpp
- test/TestTag.hpp
- test/TestValidate.cpp
- test/TestValidate.hpp
Cf. issue #447 
Don't merge if that doesn't succeed ;-)
> [win] try fixing build warnings

- cli/modules/Dump.cpp
- cli/modules/Dump.hpp
- test/TestDataAccess.cpp
> [win] Some more build warning fixes

- include/nix/NDArray.hpp
- include/nix/NDSize.hpp
- include/nix/hdf5/BaseHDF5.hpp
- src/DataArray.cpp
- src/NDArray.cpp
From size_t. Part of issue #473
> NDSizeBase<T>::nelms() return type changed to T

- src/Property.cpp
- src/hdf5/BlockHDF5.cpp
- test/TestBlock.cpp
- test/TestFile.cpp
- test/TestMultiTag.cpp
- test/TestMultiTag.hpp
- test/TestProperty.cpp
hope that brings us to the 90% :-)
> Even more tests

- CMakeLists.txt
- Remove unnecessary declarations
- Installer
- Add licenses for nix and hdf5
- Add hdf5 dlls
> CMakeList.txt: cleanup and windows installer

- README.md
As proposal, links to my Docker experiments - if you prefer not to use Docker just cancel this pull request. :)
> Updated README.md to contain Docker instructions.

- include/nix/NDSize.hpp
Added constructor for NDSizeBase that accepts vector args. Thank you
> [NDSize] add NDSizeBase constructor that accepts vector arguments

- include/nix/valid/helper.hpp
Added an empty constructor for struct Message. Thank you
> [helper.hpp] add empty constructor for struct Message

- include/nix/DataArray.hpp
- include/nix/DataType.hpp
- include/nix/Dimensions.hpp
- include/nix/base/IDataArray.hpp
- include/nix/base/IDimensions.hpp
- include/nix/hdf5/DataArrayHDF5.hpp
- include/nix/hdf5/DimensionHDF5.hpp
- src/DataType.cpp
- src/Dimensions.cpp
- src/hdf5/DataArrayHDF5.cpp
- src/hdf5/DimensionHDF5.cpp
- src/util/dataAccess.cpp
- test/TestDataAccess.cpp
- test/TestDataAccess.hpp
- test/TestDataArray.cpp
- test/TestDataArray.hpp
- test/TestDataSet.cpp
- test/TestDataSet.hpp
This pr should solve #498, (and parts of #398).
The data stored in a 1-d dataArray is used as the ticks of a RangeDimension. It is called AliasRangeDimension (we can discuss better names ;-), I would appreciate better ideas).
There are certain restrictions on this:
1. the data must be 1-D
2. the data must be numeric
Since this involves quite some changes I would really appreciate a critical review.
> Use of DataArray data as ticks in RangeDimension

- include/nix/Block.hpp
- include/nix/Exception.hpp
- include/nix/File.hpp
- include/nix/util/util.hpp
- src/Block.cpp
- src/File.cpp
- src/hdf5/BlockHDF5.cpp
- src/hdf5/FileHDF5.cpp
- src/util/util.cpp
- test/TestBlock.cpp
- test/TestFile.cpp
... first chunk of changes, please have a look.
edit:
Added the requested checkNameAndType method.
> Move checks to front-end ... 

- include/nix/DataArray.hpp
- include/nix/Dimensions.hpp
- include/nix/Feature.hpp
- include/nix/MultiTag.hpp
- include/nix/Property.hpp
- include/nix/Section.hpp
- include/nix/Source.hpp
- include/nix/Tag.hpp
- include/nix/util/util.hpp
- src/DataArray.cpp
- src/Dimensions.cpp
- src/Feature.cpp
- src/MultiTag.cpp
- src/Property.cpp
- src/Section.cpp
- src/Source.cpp
- src/Tag.cpp
- src/hdf5/BaseTagHDF5.cpp
- src/hdf5/DataArrayHDF5.cpp
- src/hdf5/DimensionHDF5.cpp
- src/hdf5/FeatureHDF5.cpp
- src/hdf5/MultiTagHDF5.cpp
- src/hdf5/PropertyHDF5.cpp
- src/hdf5/SectionHDF5.cpp
- src/hdf5/SourceHDF5.cpp
- src/util/util.cpp
- test/TestFeature.cpp
- test/TestMultiTag.cpp
- test/TestSource.cpp
- test/TestTag.cpp
Move remaining checks to front-end. This should complete issue #524.
> Front end checks

- include/nix/DataArray.hpp
- include/nix/base/IBaseTag.hpp
- include/nix/base/IDataArray.hpp
- include/nix/hdf5/BaseTagHDF5.hpp
- include/nix/hdf5/DataArrayHDF5.hpp
- src/hdf5/BaseTagHDF5.cpp
- src/hdf5/DataArrayHDF5.cpp
The last bits of issue #473. Greetings from SfN. ;)
> [m32] Use ndsize_t for object indexing everywhere now

- include/nix/DataArray.hpp
- include/nix/Dimensions.hpp
- include/nix/base/IDataArray.hpp
- include/nix/base/IDimensions.hpp
- include/nix/hdf5/DataArrayHDF5.hpp
- include/nix/hdf5/DimensionHDF5.hpp
- src/hdf5/DataArrayHDF5.cpp
- src/hdf5/DimensionHDF5.cpp
- src/util/dataAccess.cpp
- src/valid/checks.cpp
- test/TestReadOnly.hpp
- test/TestValidate.cpp
> DataArray::dimension* size_t → ndsize_t

- LICENSE
* Add main contributors to copyright holders
* This fixes #542
> LICENSE: changed to BSD 3-clause

- include/nix/Value.hpp
- src/Value.cpp
- test/TestValue.cpp
> [Value] internal representation for std::string is now char *

- include/nix/base/Entity.hpp
- include/nix/base/IEntity.hpp
- include/nix/hdf5/EntityHDF5.hpp
- include/nix/hdf5/PropertyHDF5.hpp
- include/nix/util/util.hpp
- src/Block.cpp
- src/Feature.cpp
- src/File.cpp
- src/Group.cpp
- src/MultiTag.cpp
- src/Section.cpp
- src/Source.cpp
- src/Tag.cpp
- src/hdf5/EntityHDF5.cpp
- src/hdf5/PropertyHDF5.cpp
- test/BaseTestBlock.cpp
- test/BaseTestFeature.cpp
- test/BaseTestFile.cpp
- test/BaseTestGroup.cpp
- test/BaseTestMultiTag.cpp
- test/BaseTestSection.cpp
- test/BaseTestSource.cpp
- test/BaseTestTag.cpp
Front facing classes check passed entities for none and if the are valid in the backend
This pr should solve issue #565
> Improved Input checking

- README.md
as works for me using Linux Mint
> [readme] add note about skipping builtin boost cmake

- include/nix/Value.hpp
- include/nix/Variant.hpp
- src/Value.cpp
- src/Variant.cpp
- test/Runner.cpp
- test/TestValue.cpp
- test/TestVariant.cpp
- test/TestVariant.hpp
> Split variant part from Value

- release_instructions.md
This file includes only the linux/ubuntu/launchpad instructions. Please fill in missing stuff
> realease instructions

- CMakeLists.txt
include(CTest) adds the BUILD_TESTING option,
and we and only add tests if it is not set to OFF
> [cmake] honour -DBUILD_TESTING=OFF

- include/nix/Value.hpp
- src/Value.cpp
> Value: is not a Variant anymore

- README.md
We are included in homebrew science as nixio. Yay!
> [README] update osx install (homebrew/sccience)

- backend/hdf5/h5x/H5DataSet.cpp
- backend/hdf5/h5x/H5DataType.cpp
- backend/hdf5/h5x/H5DataType.hpp
- test/hdf5/TestH5.cpp
Functionality now is in h5x::DataType.
> Remove CompoundType class

- src/DataArray.cpp
- src/DataType.cpp
- src/Dimensions.cpp
- test/BaseTestDataArray.cpp
DataArray : Line 35 : oirign -> origin
Dimensions : Line 178 : smae -> same
> Fix various typos

- Win32.md
> nix/Win32.md: Minor Typo error

- Contributing.md
- README.md
> Minor typo error

- CMakeLists.txt
> Fix cmake FindHDF5 issue

- include/nix/Dimensions.hpp
- src/Dimensions.cpp
- changes axis, operator, tickAt and positionAt of Range- and SampledDimension from size_t to ndsize_t
- adds size checks before assigning ndsize_t variable to size_t
Closes #628
> [Dimensions] move from size_t to ndsize_t

- README.md
- install_linux.md
- install_mac.md
- install_win.md
force pushing to master was too krass for me :)
> update readme and move some stuff to extra files

- include/nix/Dimensions.hpp
- include/nix/util/dataAccess.hpp
- src/Dimensions.cpp
- src/util/dataAccess.cpp
> Dimension: indexOf should return a ndsize_t

- backend/hdf5/FileHDF5.cpp
- backend/hdf5/FileHDF5.hpp
- docs/versioning.md
- include/nix.hpp
- include/nix/Version.hpp
- test/BaseTestFile.hpp
- test/Runner.cpp
- test/TestVersion.cpp
- test/TestVersion.hpp
- test/hdf5/TestFileHDF5.cpp
- test/hdf5/TestFileHDF5.hpp
See issue #596
File system backend is not done yet.
> Implement version compatibility checking

- CMakeLists.txt
I would like to publish the cmake fix as 1.3.1 so we need to increase the patch version...
> increase version number to 1.3.1

- CMakeLists.txt
actually, I just want to have appveyor building it :)
> [CMakeLists] version bump

- CMakeLists.txt
- backend/fs/DataArrayFS.cpp
- backend/fs/DataArrayFS.hpp
- backend/fs/DimensionFS.cpp
- backend/fs/DimensionFS.hpp
- backend/fs/EntityWithMetadataFS.cpp
- backend/fs/EntityWithMetadataFS.hpp
- backend/fs/EntityWithSourcesFS.cpp
- backend/fs/EntityWithSourcesFS.hpp
- backend/fs/NamedEntityFS.cpp
- backend/fs/NamedEntityFS.hpp
- include/nix/DataType.hpp
- include/nix/Platform.hpp
- include/nix/base/IFile.hpp
- include/nix/util/util.hpp
> Replacement for apparently stalled pr from The-E

- docs/versioning.md
In addition to the compatibility rules for file format versions, we should also explain how library version compatibility works.
Some aspects of this we haven't discussed in detail, so let me know if you agree with the rules.
> Description of library version compatibility rules

- docs/inheritance.txt
Fix some mistakes in the inheritance model and also complete it for the backend and frontend.
> Docs: inheritance description update

- backend/fs/BaseTagFS.cpp
- backend/fs/EntityWithSourcesFS.cpp
- backend/hdf5/BaseTagHDF5.cpp
- backend/hdf5/EntityWithSourcesHDF5.cpp
- src/Group.cpp
- test/BaseTestEntityWithSources.cpp
- test/BaseTestEntityWithSources.hpp
- test/hdf5/TestEntityWithSourcesHDF5.hpp
replacement for PR #686 
also simplifies the generic vector setter in Group and the DataArray setters in BaseTagFS/HDF5
> again the sources

- CMakeLists.txt
> [cmake] 1.4 version bump

- src/File.cpp
- src/Section.cpp
- test/BaseTestSection.cpp
> Section find does not include self in result set 

- include/nix/File.hpp
- src/File.cpp
- test/BaseTestSection.cpp
> fix max_depth pass through and extend tests

- .dir-locals.el
> Fix .dir-locals.el to unbreak emacs indent

- backend/fs/BlockFS.cpp
- backend/fs/BlockFS.hpp
- backend/fs/DataArrayFS.cpp
- backend/fs/DataArrayFS.hpp
- backend/fs/FileFS.cpp
- backend/fs/FileFS.hpp
- backend/hdf5/BlockHDF5.cpp
- backend/hdf5/BlockHDF5.hpp
- backend/hdf5/DataArrayHDF5.cpp
- backend/hdf5/DataArrayHDF5.hpp
- backend/hdf5/FileHDF5.cpp
- backend/hdf5/FileHDF5.hpp
- backend/hdf5/h5x/H5Group.cpp
- backend/hdf5/h5x/H5Group.hpp
- include/nix.hpp
- include/nix/Block.hpp
- include/nix/Compression.hpp
- include/nix/DataArray.hpp
- include/nix/File.hpp
- include/nix/base/IBlock.hpp
- include/nix/base/IDataArray.hpp
- include/nix/base/IFile.hpp
- src/Block.cpp
- src/File.cpp
addresses #510 
this is more a quick and dirty implementation of compression support. It uses a hdf5 built-in compression algorithm with a fixed compression level. At the moment, one can decide for each dataArray to compress it or not, default it true.
This pr is meant to get us thinking about how it should actually work. For the moment, I would prefer  such a simple solution which could be elaborated in future versions, or upon user request...
> Compression support

- include/nix/DataArray.hpp
- include/nix/Group.hpp
- include/nix/Section.hpp
- include/nix/Source.hpp
- include/nix/Tag.hpp
- test/BaseTestDataArray.cpp
> Fix linux build warnings

- cli/modules/Validate.cpp
- include/nix/base/NamedEntity.hpp
- include/nix/valid/conditions.hpp
- include/nix/valid/helper.hpp
- include/nix/valid/result.hpp
- src/valid/result.cpp
Fix issue #705 
My eyes still hurt from looking at some of the code ...
> Print entity name during validation

- src/valid/validate.cpp
> [valid] must -> should for non-SI units of DAs

- include/nix/base/NamedEntity.hpp
- test/TestValidate.cpp
See if we can fix issue #705 for good now.
> Fix getEntityName on windows

- backend/fs/BlockFS.cpp
- backend/fs/BlockFS.hpp
- backend/hdf5/BlockHDF5.cpp
- backend/hdf5/BlockHDF5.hpp
- backend/hdf5/DataFrameHDF5.cpp
- backend/hdf5/DataFrameHDF5.hpp
- backend/hdf5/FileHDF5.hpp
- backend/hdf5/GroupHDF5.cpp
- backend/hdf5/GroupHDF5.hpp
- backend/hdf5/h5x/H5DataType.cpp
- include/nix.hpp
- include/nix/Block.hpp
- include/nix/DataFrame.hpp
- include/nix/Group.hpp
- include/nix/ObjectType.hpp
- include/nix/base/IBlock.hpp
- include/nix/base/IDataFrame.hpp
- src/Block.cpp
- src/DataFrame.cpp
- src/Group.cpp
- test/BaseTestBlock.cpp
- test/BaseTestBlock.hpp
- test/BaseTestDataFrame.cpp
- test/BaseTestDataFrame.hpp
- test/BaseTestGroup.cpp
- test/BaseTestGroup.hpp
- test/Runner.cpp
- test/hdf5/TestBlockHDF5.hpp
- test/hdf5/TestDataFrameHDF5.hpp
- test/hdf5/TestGroupHDF5.hpp
This is a test balloon to see where if (I am sure it will) breaks on other platforms (win?).
It is mostly done. Mostly. Need more tests, as always.
Feedback on the API would also be good. Some bits are missing and some are to be discussed:
- Appending rows (currently done via `rows(NEW_SIZE)`)?
- FS backend and resizing of rows.
> DataFrame [WIP]

- backend/hdf5/DataFrameHDF5.cpp
> [DataFrame] remove unused capture in lambda

- CMakeLists.txt
- nixio.pc.in
Next step of the big rename (issue #595)
> [cmake] rename nix lib to nixio

- CMakeLists.txt
And the next step of the big rename (issue #595)
> [cmake] rename nix-tool to nixio-tool

- include/nix/DataArray.hpp
- test/BaseTestDataArray.cpp
Add default arguments for the appendXYZDimension methods.
I do not remember if there was a decision against default values, but I find them quite convenient :) And they actually save me from writing very boring lines of code...
> Dimensions

- docs/data_model.md
- docs/file_handling.md
- docs/getting_started.md
- docs/storing_data.md
- docs/tagging.md
I went through the docs so far and made some minor changes and typo fixes. Hope you like them. Great work on the docs so far.
> Docs: Minor quick review

- .travis.yml
... homebrew science does not exist any more ...
> [travis] fix osx build

- include/nix/util/dataAccess.hpp
- include/nix/valid/conditions.hpp
- src/util/dataAccess.cpp
- src/valid/checks.cpp
- test/BaseTestDataAccess.cpp
- test/BaseTestDataAccess.hpp
- test/hdf5/TestDataAccessHDF5.hpp
... upon successful build and merge we may want to pick these changes to 1.4 as well.
> Implement data slice method

- include/nix/MultiTag.hpp
- include/nix/util/filter.hpp
- test/BaseTestMultiTag.cpp
- test/BaseTestSource.cpp
* **DataView** has a getter for the dimensions of the underlying data which simplifies working with data retrieved from a Tag/Mtag
* **MultiTag** has a positionCount method which simplifies reading the number of tagged positions
* **NameFilter** and **TypeFilter** can now be constructed with custom regular expressions. Not sure if it makes sense to add this to IdFilter too?
> adds a little bit of sugar

- Doxyfile.in
- docs/data_handling.md
- docs/finding_things.md
- docs/getting_started.md
- docs/index.md
- docs/standardization.md
- include/nix/Block.hpp
- include/nix/DataArray.hpp
- include/nix/DataFrame.hpp
- include/nix/Dimensions.hpp
- include/nix/File.hpp
- include/nix/Group.hpp
- include/nix/Section.hpp
- include/nix/base/NamedEntity.hpp
- include/nix/util/dataAccess.hpp
I wonder if there is something missing in the documentation, please let me know
> improved doxygen settings, several fixes of the documentation

- appveyor.yml
- include/nix/DataArray.hpp
- include/nix/Dimensions.hpp
- include/nix/MultiTag.hpp
- include/nix/Tag.hpp
- include/nix/util/dataAccess.hpp
- include/nix/util/filter.hpp
- include/nix/valid/conditions.hpp
- src/Dimensions.cpp
- src/MultiTag.cpp
- src/util/dataAccess.cpp
- src/valid/checks.cpp
- test/BaseTestDataAccess.cpp
- test/BaseTestDataAccess.hpp
- test/BaseTestDataArray.cpp
- test/BaseTestDimension.cpp
- test/BaseTestMultiTag.cpp
- test/BaseTestSource.cpp
- test/BaseTestTag.cpp
- test/hdf5/TestDataAccessHDF5.hpp
> cherry picks from master

- docs/annotating.md
- docs/index.md
fixed broken link and updated odml link to new version
> Documentation update

- backend/hdf5/h5x/H5Exception.hpp
- cli/modules/IModule.hpp
- include/nix/util/filter.hpp
- include/nix/valid/checks.hpp
Got quite a few. See this [build](https://cdash.0xdeadbabe.info/viewBuildError.php?type=1&buildid=7404).
> Fix compile warnings on clang 9

- backend/hdf5/DataArrayHDF5.cpp
- backend/hdf5/PropertyHDF5.hpp
- backend/hdf5/h5x/Attribute.hpp
- backend/hdf5/h5x/DataSpace.hpp
- backend/hdf5/h5x/H5DataSet.hpp
- backend/hdf5/h5x/H5DataType.hpp
- backend/hdf5/h5x/H5Group.hpp
- backend/hdf5/h5x/LocID.hpp
- cli/modules/Dump.cpp
- include/nix/Block.hpp
- include/nix/DataArray.hpp
- include/nix/Dimensions.hpp
- include/nix/Feature.hpp
- include/nix/File.hpp
- include/nix/Group.hpp
- include/nix/Identity.hpp
- include/nix/MultiTag.hpp
- include/nix/Property.hpp
- include/nix/Section.hpp
- include/nix/Source.hpp
- include/nix/Tag.hpp
- include/nix/hydra/multiArray.hpp
- src/util/dataAccess.cpp
not done
edit:
should be enough for now :)
> fix alerts reported by lgtm

- test/hdf5/TestDataArrayHDF5.hpp
- test/hdf5/TestDataSet.cpp
- Fix a loop condition
- Enable an existing test
> Small test fixes

- README.md
- docs/api_doc/Doxyfile
- docs/conf.py
- docs/index.rst
using breathe and exhale for converting doxygen xml output to sphinx rendered html
> Docs again

- README.md
- docs/getting_started.rst
- docs/index.md
> Fix broken nixpy tutorial link in README

- include/nix/Exception.hpp
- include/nix/util/dataAccess.hpp
- src/Dimensions.cpp
- src/util/dataAccess.cpp
- test/BaseTestDataAccess.cpp
- test/BaseTestDataAccess.hpp
- test/BaseTestDataArray.cpp
- test/hdf5/TestDataAccessHDF5.hpp
not completely done yet. Needs a bit more testing and  support for column if a default unit is specified
> Data access df dim

- .gitignore
- docs/slicing_and_indices.md
... addresses issue #818 
Please feel free to comment.
> sketch of a specification of indexing and slicing rules
